<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <LangVersion>latest</LangVersion>
        <AssemblyName>NeoPlus</AssemblyName>
        <RootNamespace>NeoPlus</RootNamespace>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
    </PropertyGroup>

    <!-- Game path -->
    <Import Project="Local.props" Condition="Exists('Local.props')"/>
    <Target Name="EnsureGamePath" BeforeTargets="ResolveReferences">
        <Error
                Condition="'$(NeoGameDir)' == ''"
                Text="NeoGameDir is not set. Generate Local.props or set the property manually."/>
    </Target>

    <ItemGroup>
        <Reference Include="MelonLoader">
            <HintPath>$(NeoGameDir)\MelonLoader\net6\MelonLoader.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="0Harmony">
            <HintPath>$(NeoGameDir)\MelonLoader\net6\0Harmony.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Il2CppInterop.Runtime">
            <HintPath>$(NeoGameDir)\MelonLoader\net6\Il2CppInterop.Runtime.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Assembly-CSharp">
            <HintPath>$(NeoGameDir)\MelonLoader\Il2CppAssemblies\Assembly-CSharp.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Il2Cppmscorlib">
            <HintPath>$(NeoGameDir)\MelonLoader\Il2CppAssemblies\Il2Cppmscorlib.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="Unity.TextMeshPro">
            <HintPath>$(NeoGameDir)\MelonLoader\Il2CppAssemblies\Unity.TextMeshPro.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="UnityEngine.CoreModule">
            <HintPath>$(NeoGameDir)\MelonLoader\Il2CppAssemblies\UnityEngine.CoreModule.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="UnityEngine.InputLegacyModule">
            <HintPath>$(NeoGameDir)\MelonLoader\Il2CppAssemblies\UnityEngine.InputLegacyModule.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="UnityEngine.TextRenderingModule">
            <HintPath>$(NeoGameDir)\MelonLoader\Il2CppAssemblies\UnityEngine.TextRenderingModule.dll</HintPath>
            <Private>False</Private>
        </Reference>
        <Reference Include="UnityEngine.UI">
            <HintPath>$(NeoGameDir)\MelonLoader\Il2CppAssemblies\UnityEngine.UI.dll</HintPath>
            <Private>False</Private>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="MinHook.NET" Version="1.1.2"/>
    </ItemGroup>

    <ItemGroup>
      <None Update="THIRD-PARTY-NOTICES.txt">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>
</Project>
